# :see: https://packaging.python.org/en/latest/specifications/declaring-project-metadata

[project]
name = "py-tty-day-1"
version = "1.0.0"
description = "Katas for Python Tech Transformation Workshop day 1"
readme = "README.rst"
requires-python = ">= 3.12"
license = { text = "© 2023 PHX Limited - All Rights Reserved" }
authors = [
    { email = "Phoenix Zerin <phx@phx.nz>" }
]

dependencies = [
]

[tool.autohooks]
mode = "pipenv"
pre-commit = [
    "autohooks.plugins.black",
    "autohooks.plugins.ruff",
    "autohooks.plugins.pytest"
]
